# Site settings
title: SparkPost Developer Community Hub
email: developers@sparkpost.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://developers.sparkpost.com" # the base hostname & protocol for your site
twitter_username: SparkPost
github_username:  SparkPost

collections:
  contributors:
    output: true
  videos:
    output: true


# Build settings
markdown: kramdown
sass:
    load_paths:
        - _sass
        - bower_components/bootstrap-sass/assets/stylesheets
