# Site settings
environment: production
title: SparkPost Developer Hub
email: developers@sparkpost.com
description: >
  SparkPost provides email delivery and analytics built for
  developers. Our developer hub is a collection of resources to help you succeed
  with SparkPost. What will you build?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://developers.sparkpost.com" # the base hostname & protocol for your site
twitter_username: SparkPost
github_username:  SparkPost
facebook_username: SparkPost
facebook_app_id: 1078423545531734
highlighter: pygments
mixpanel_token: 0c8d92f4bd11446215bd4e7cb7639933

collections:
  contributors:
    output: true
  videos:
    output: true

defaults:
  - scope:
      path: ""
      type: videos
    values:
      layout: video
      video_height: 315
      video_width: 560
  - scope:
      path: ""
      type: contributors
    values:
      layout: contributor

# Build settings
markdown: kramdown
